fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    "tea": "https://github.com/voxpupuli/puppet-tea.git"
  symlinks:
    "ntp": "#{source_dir}"
    "my_ntp": "#{source_dir}/spec/fixtures/my_ntp"
